version: "3.8"

services:
  php:
    tty: true
    restart: always
    build: .
    ports:
      - "${SERVE_PORT}:8000"
    container_name: mandana_chemistry-backend
    command:
      "php artisan octane:start --host=0.0.0.0"
    networks:
        - mandana_chemistry-network
networks:
    mandana_chemistry-network:
        driver: bridge
        external: true
