services:
    php:
        tty: true
        restart: always
        build: .
        ports:
            - "${SERVE_PORT}:8000"
            - "8080:8080"
        container_name: mandana_chemistry-backend
        volumes:
            - ./storage/app:/app/storage/app:rwz
            - ./storage/logs:/app/storage/logs:rwz
        networks:
            - mandana_chemistry-network
networks:
    mandana_chemistry-network:
        driver: bridge
        external: true
