name: deploy

on:
  push:
    branches:
      - main
jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - name: Pull from repository
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/qc/mandana_chemistry/mandana_chemistry_backend
            git pull origin main
  build:
    needs: [ pull ]
    runs-on: ubuntu-latest
    steps:
      - name: Build and restart container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/qc/mandana_chemistry/mandana_chemistry_backend
            docker compose down
            docker compose build
            docker compose up -d
